### PR TITLE
Use LLVM fcmp une instead of fcmp one

### PR DESCRIPTION
**Pull request by greg-lunarg**
To more accurately implement GLSL/ELSL semantics for float !=

### CODE REVIEW

**Comment by johnkslang** [comment]
Is the point to change NaN semantics?

What impact does this have on if (Nan != NaN)?

**Comment by greg-lunarg** [comment]
The point is to utilize the LLVM operation with the same semantics as IEEE
and GLSL.

By my reading, IEEE rules says that NAN != x is true for all values of x
including NAN.

The following are from LLVM's definiton of fcmp:

one: yields true if both operands are not a QNAN and op1 is not equal to op2
une: yields true if either operand is a QNAN or op1 is not equal to op2

So "fcmp one" gives false for != when either value is NAN. "fcmp une"
behavior matches my reading of IEEE rules. So it seems "une" should be
generated for GLSL floating point !=.

It does seem unintuitive to use LLVM ordered semantices for all fcmp
flavors except !=, but I think that is what is called for.

**Comment by johnkslang** [comment]
GLSL is silent on this, and for IEEE, I had thought all comparisons involving a NaN should result in false, except of course both flavors are provided so you can get what you want.  Probably I'm missing the motivation for this.

If source code said `a == b`, and that's an ordered equal, and then the compiler wants to reverse the sense of it, the opposite of an ordered equal is an unordered not equal.

So, one question is whether you want `! (a == b)` to mean the same thing as `(a != b)`, or if we want to allow some distinction.  Would you start arguing the same for `a < b` vs. `a >=b`?

Just trying to understand a bit better... Thanks.

**Comment by greg-lunarg** [comment]
While GLSL is "silent" here, I believe that IEEE semantics is at least
accomodated if not desired.

I believe that x != x is indeed true for x being NaN. I can't put my finger
on the IEEE spec at the moment, but this is a quote from Kahan's lecture
notes:

"The exceptions are C predicates “ x == x ” and “ x != x ”, which are
respectively 1 and 0 for every infinite or finite number x but reverse if x
is Not a Number ( NaN );"

The following experiment on an x86 processor seems to corroborate:

greg@gsfdev:~/junk$ cat t.c

#include <math.h>
#include <stdio.h>

double g = -1;

main()
{
    double f = sqrt(g);
    if (f == f)
        printf("f == f true\n");
    else
        printf("f == f false\n");
    if (f != f)
        printf("f != f true\n");
    else
        printf("f != f false\n");
}

greg@gsfdev:~/junk$ g++ t.c
greg@gsfdev:~/junk$ ./a.out
f == f false
f != f true
greg@gsfdev:~/junk$

If you need a quote from the spec, I can get that with a little more
effort. Let me know.

The preceding seems to suggest that x != x is true if x is Nan. Thus, in
order to express IEEE semantics for !=, we need to utilize fcmp une.

LLVM "reverses" une to oeq and vice-versa (I can provide output if needed),
so I believe IEEE behavior is preserved by LLVM.

So as unintuitive as it seems, it seems glslang should use unordered for
!=, and ordered for all other compares in Top IR.

**Pull request merged**
